### ISSUE TITLE
Would be nice to have less subfolders

### ISSUE THREAD

**Issue by patrickpaap** [IvoLimmen/photoarchive#7]
**YEAR > MONTH-DAY**

Create a folder 2016, with a sub-folders 11-23, 11-25, 11-28 etc.

2016>11-23 Kids are playing with snow
2016>11-25 Kat is puking in our garden
2016>11-28 Efteling theme park
Etc.

A short description is to be added manually afterwards of course.

**Comment by IvoLimmen** [comment]
Would be interesting to see if I can add it as an option. Maybe even make the directory structure scriptable.

**Comment by patrickpaap** [comment]
For me it's a must have and a great enhancement to this great time saving tool.
