### ISSUE TITLE
Videos are not being copied to the right folder

### ISSUE THREAD

**Issue by patrickpaap** [IvoLimmen/photoarchive#8]
![bug_video](https://cloud.githubusercontent.com/assets/26500186/24073392/64bb3b4a-0bf7-11e7-969d-c5c4ef68937c.PNG)

Prefer EXIF was checked

**Comment by IvoLimmen** [comment]
Not all video files have metadata. I have check several video's I own; created myself and by other all different devices. None of the files I have have metadata. You can check yourself using VLC then press CTRL-i; this will open the metadata.
It your video do have some metadata, please send me one (if it is not read) and I will look if I can fix it. For now I will close the issue.
